main/urls.py
from django.urls import path
from . import views

app_name='main'

urlpatterns = [
    path('', views.welcome, name='welcome'),
    path('gerb/', views.gerb, name='gerb'),
    path('bayroq/', views.bayroq, name='bayroq'),
    path('madhiya/', views.madhiya, name='madhiya'),
    path('vazifa/', views.vazifa, name='vazifa'),
    path('rektorat/', views.rektorat, name='rektorat'),
    path('qabulxona/', views.qabul, name='qabulxona'),
    # path('qabulxona/xabar', views.store, name='xabar'),           shu yer chala
    path('i-xizmatlar/', views.xizmatlar, name='xizmatlar'),
    path('sahifa/<str:page>/', views.sahifalar, name='sahifa'),
    path('markazlar/', views.markazlar, name='markazlar'),
    path('markaz/<int:pk>/', views.markaz, name='markaz'),
    path('yangiliklar/', views.yangiliklar, name='yangiliklar'),
    path('yangilik/<int:pk>/', views.yangilik, name='yangilik'),
    path('antikorrupsiya/', views.antikorrupsiya, name='antikorrupsiya'),

]

tsdi_uz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = i18n_patterns(
    path('', include('main.urls', namespace='main')),
    path('', include('fakultet.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('ckeditor/', include('ckeditor_uploader.urls')),

)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField

class Partner (models.Model):  # hamkorlar
    name = models.CharField(max_length=250, verbose_name='Name') # Translation
    image = models.ImageField(upload_to='./partner/', verbose_name='Image')
    url = models.URLField(verbose_name='Url')

    def __str__(self):
        return self.name


class Department(models.Model):  #Markazlar
    name = models.CharField(max_length=250, verbose_name='Markaz nomi') #Translation
    content = RichTextUploadingField(verbose_name='Content') #Translation

    sees = models.IntegerField(default=1, verbose_name="Kurilganlar")

    create_at = models.DateTimeField(auto_now_add=True, verbose_name='Create time')
    update_at = models.DateTimeField(auto_now=True, verbose_name='Update time')

    def __str__(self):
        return self.name

class Employee(models.Model):   #markazlar ishchilari
    name = models.CharField(max_length=200, verbose_name='F.I.O')
    image = models.ImageField(default='./employee/avatar.png', upload_to='./employee', null=True, blank=True)
    email = models.EmailField(verbose_name='Email', null=True, blank=True)
    phone_number = models.CharField(max_length=50, verbose_name='Telefon')
    academic_title = models.TextField(null=True, blank=True)
    position = models.CharField(max_length=200, null=True, blank=True) #Translation  --------

    is_chief = models.BooleanField(default=False)
    reception_time = RichTextUploadingField(null=True, blank=True) #Translation

    department = models.ForeignKey(Department, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Rectory(models.Model):  # rektorat
    name = models.CharField(max_length=200, verbose_name='F.I.O')
    image = models.ImageField(upload_to='./rectory/', verbose_name='Image')
    content = RichTextUploadingField(verbose_name="Information") #Translation
    academic_title = models.CharField(max_length=200, verbose_name='Academic Title') #Translation  ------
    address = models.TextField(verbose_name='Address', null=True, blank=True) #Translation

    phone_number = models.CharField(max_length=50, verbose_name='Phone Number', null=True, blank=True)
    fax_number = models.CharField(max_length=50, verbose_name='Fax Number', null=True, blank=True)
    email = models.EmailField(verbose_name='Email', null=True, blank=True)
    facebook = models.CharField(max_length=100, verbose_name='Facebook', null=True, blank=True)
    instagram = models.CharField(max_length=100, verbose_name='Instagram', null=True, blank=True)
    telegram = models.CharField(max_length=100, verbose_name='Telegram', null=True, blank=True)

    is_rector = models.BooleanField(default=False)
    position = models.CharField(max_length=250, verbose_name='Position') #Translation ------
    reception_time = RichTextUploadingField(verbose_name='Qabul vaqti') #Translation

    def __str__(self):
        return self.name


class Service(models.Model):
    name = models.CharField(max_length=200, verbose_name='Name')
    icon_class = models.CharField(max_length=250, verbose_name='Icon Name')
    url = models.URLField(verbose_name='Url')

    def __str__(self):
        return self.name


class Sahifalar(models.Model):
    title = models.CharField(max_length=255, verbose_name='Title')
    content = RichTextUploadingField(verbose_name='Content')
    page_name = models.CharField(max_length=255, verbose_name='Page url')

    def __str__(self):
        return self.page_name

main/views.py
from django.shortcuts import render
from .models import Partner, Department, Employee, Rectory, Service, Sahifalar
from fakultet.models import Chair, TeacherChair, Faculty, TeacherFaculty, New

def welcome(request):
    partners = Partner.objects.all() # hamkorlar
    faculties = Faculty.objects.all()
    news = New.objects.all()[:8]
    content = {
        'partners': partners,
        'faculties': faculties,
        'news': news
    }
    return render(request, 'main/welcome.html', content)

def gerb(request):
    content = {
        'faculties': Faculty.objects.all()
    }
    return render(request, 'main/ramzlar/gerb.html', content)

def bayroq(request):
    content = {
        'faculties': Faculty.objects.all()
    }
    return render(request, 'main/ramzlar/bayroq.html', content)

def madhiya(request):
    content = {
        'faculties': Faculty.objects.all()
    }
    return render(request, 'main/ramzlar/madhiya.html', content)

def vazifa(request):
    content = {
        'faculties': Faculty.objects.all()
    }
    return render(request, 'main/ramzlar/vazifa.html', content)

def rektorat(request):
    rectories = Rectory.objects.all()
    rector = None
    unrector = []
    for rectory in rectories:
        if rectory.is_rector:
            rector = rectory
        else:
            unrector.append(rectory)
    content = {
        'rector': rector,
        'rectories': unrector,
        'faculties': Faculty.objects.all()
    }
    return render(request, 'main/rektorat.html', content)


def qabul(request):

    content = {
        'faculties': Faculty.objects.all()
    }
    return render(request, 'main/qabulxona.html', content)

def store(request):  #chala
    pass

def xizmatlar(request):
    services = Service.objects.all()
    content = {
        'services': services,
        'faculties': Faculty.objects.all()
    }
    return render(request, 'main/xizmatlar.html', content)

def sahifalar(request, page):
    sahifa = Sahifalar.objects.get(page_name=page)
    content = {
        'sahifa': sahifa,
        'faculties': Faculty.objects.all(),
    }
    return render(request, 'main/page.html', content)

def markazlar(request):
    departments = Department.objects.all()
    content = {
        'departments': departments,
        'faculties': Faculty.objects.all()
    }
    return render(request, 'main/markazlar.html', content)

def markaz(request, pk):
    department = Department.objects.get(id=pk)
    employees = Employee.objects.filter(department=department)
    chief = None
    xodimlar = []
    for employee in employees:
        if employee.is_chief:
            chief = employee
        else:
            xodimlar.append(employee)
    content = {
        'department': department,
        'chief': chief,
        'employees': xodimlar,
        'faculties': Faculty.objects.all(),
    }
    return render(request, 'main/markaz.html', content)

def yangiliklar(request):
    news = New.objects.all()
    content = {
        'news': news,
        'faculties': Faculty.objects.all(),
    }
    return render(request, 'main/yangiliklar.html', content)

def yangilik(request, pk):
    new = New.objects.get(id=pk)
    news = New.objects.all()[:5]
    content ={
        'new': new,
        'news': news,
        'faculties': Faculty.objects.all(),
    }
    return render(request, 'main/yangilik.html', content)


def antikorrupsiya(request):
    content = {
        'faculties': Faculty.objects.all()
    }
    return render(request, 'main/korupsiya/korrupsiya.html', content)

templates/main/korupsiya/korrupsiya.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="markaz-title" style="background-image: url({% static 'assets/images/medik.jpg' %})">
        <p>Korrupsiyaga qarshi kurash</p>
        <ul>
            <li><a href="/">Asosiy sahifa</a></li>
            <li><a href="#"></a></li>
        </ul>
    </div>
    <section class="markaz-blog" style="background-image:url(https://www.gov.uz/img/title_bg.png)">
        <div class="korrup-blogs">
            <div class="korrup-left">
                <nav>
                    <a href="{% url 'main:sahifa' 'korrupsiya-normativ-huquqiy-hujjatlar' %}"><p class="k-sahifa">
                        Normativ-huquqiy hujjatlar</p></a>
                    <a href="#"><p class="k-sahifa">Amalga oshiriligan ishlar</p></a>
                    <a href="#"><p class="k-sahifa">KQK "Komplayens nazorat" TBB faoliyati to`g`risida</p></a>
                    <br>
                    <hr>
                    <br>
                    <p class="p-contact"><a><i class="fa fa-fax"></i> +998 (71) 230-48-05</a></p>
                    <br>
                    <p class="p-contact"><a href="https://t.me/+j6xVYKwaMbwzNjgy"><i class="fa fa-paper-plane"></i>
                        Telegram sahifasi</a></p>
                </nav>
            </div>
            <div class="korrup-main">
                <div class="korrupsiya-main">
                    <h2>Korrupsiyaga qarsgi kurashish oid faoliyat</h2>
                    <br><br>
                    <nav>
                        <nav class="korrupsiya-video">
                            <video style="border-radius: 2px" width="49%" height="auto" controls>
                                <source src="https://tsdi.uz/storage/korrupsiya/Vijdon_saratoni_hujjatli_filmi_%D0%94%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9_%D1%84%D0%B8%D0%BB%D1%8C%D0%BC_%C2%AB%D0%A0%D0%B0%D0%BA_%D1%81%D0%BE%D0%B2%D0%B5%D1%81%D1%82%D0%B8%C2%BB.mp4"
                                        type="video/mp4">
                                <source src="" type="video/ogg">
                            </video>
                            <video style="border-radius: 2px" width="49%" height="auto" controls>
                                <source src="https://tsdi.uz/storage/korrupsiya/rolik%201%20(2).mp4" type="video/mp4">
                                <source src="" type="video/ogg">
                            </video>
                        </nav>
                        <br><br><br>
                        <nav class="korrupsiya-video">
                            <video style="border-radius: 2px" width="49%" height="auto" controls>
                                <source src="https://tsdi.uz/storage/korrupsiya/%D0%9A%D0%BE%D1%80%D1%80%D1%83%D0%BF%D1%86%D0%B8%D1%8F%20%D0%BA%D0%B5%D0%BB%D0%B0%D0%B6%D0%B0%D0%BA%20%D0%BA%D1%83%D1%88%D0%B0%D0%BD%D0%B4%D0%B0%D1%81%D0%B8_1.mp4"
                                        type="video/mp4">
                                <source src="" type="video/ogg">
                            </video>
                            <video style="border-radius: 2px" width="49%" height="auto" controls>
                                <source src="https://tsdi.uz/storage/korrupsiya/%D0%9A%D0%BE%D1%80%D1%80%D1%83%D0%BF%D1%86%D0%B8%D1%8F%20%E2%80%94%20%D1%82%D0%B0%D1%80%D0%B0%D2%9B%D2%9B%D0%B8%D1%91%D1%82%D0%B3%D0%B0%20%D2%9B%D0%B0%D1%80%D1%88%D0%B8%20%D0%B6%D0%B8%D0%BD%D0%BE%D1%8F%D1%82!.mp4"
                                        type="video/mp4">
                                <source src="" type="video/ogg">
                            </video>
                        </nav>
                    </nav>
                </div>
            </div>
        </div>
    </section>
{% endblock %}