fakultet/urls.py
from django.urls import path
from . import views

app_name = 'faculty'
urlpatterns = [
    path('fakultetlar/', views.faculties_view, name='fakultetlar'),
    path('fakultet/<str:sub_name>/', views.faculty_view, name='fakultet'),
    path('kafedralar/', views.kafedralar_view, name='kafedralar'),
    path('kafedra/<str:sub_name>/', views.kafedra_view, name='kafedra'),
]

main/urls.py
from django.urls import path
from . import views

app_name='main'

urlpatterns = [
    path('', views.welcome, name='welcome'),
    path('gerb/', views.gerb, name='gerb'),
    path('bayroq/', views.bayroq, name='bayroq'),
    path('madhiya/', views.madhiya, name='madhiya'),
    path('vazifa/', views.vazifa, name='vazifa'),
    path('rektorat/', views.rektorat, name='rektorat'),
    path('qabulxona/', views.qabul, name='qabulxona'),
    # path('qabulxona/xabar', views.store, name='xabar'),           shu yer chala
    path('i-xizmatlar/', views.xizmatlar, name='xizmatlar'),
    path('sahifa/<str:page>/', views.sahifalar, name='sahifa'),
    path('markazlar/', views.markazlar, name='markazlar'),
    path('markaz/<int:pk>/', views.markaz, name='markaz'),
    path('yangiliklar/', views.yangiliklar, name='yangiliklar'),
    path('yangilik/<int:pk>/', views.yangilik, name='yangilik'),
    path('antikorrupsiya/', views.antikorrupsiya, name='antikorrupsiya'),

]

tsdi_uz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = i18n_patterns(
    path('', include('main.urls', namespace='main')),
    path('', include('fakultet.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('ckeditor/', include('ckeditor_uploader.urls')),

)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField

class Partner (models.Model):  # hamkorlar
    name = models.CharField(max_length=250, verbose_name='Name') # Translation
    image = models.ImageField(upload_to='./partner/', verbose_name='Image')
    url = models.URLField(verbose_name='Url')

    def __str__(self):
        return self.name


class Department(models.Model):  #Markazlar
    name = models.CharField(max_length=250, verbose_name='Markaz nomi') #Translation
    content = RichTextUploadingField(verbose_name='Content') #Translation

    sees = models.IntegerField(default=1, verbose_name="Kurilganlar")

    create_at = models.DateTimeField(auto_now_add=True, verbose_name='Create time')
    update_at = models.DateTimeField(auto_now=True, verbose_name='Update time')

    def __str__(self):
        return self.name

class Employee(models.Model):   #markazlar ishchilari
    name = models.CharField(max_length=200, verbose_name='F.I.O')
    image = models.ImageField(default='./employee/avatar.png', upload_to='./employee', null=True, blank=True)
    email = models.EmailField(verbose_name='Email', null=True, blank=True)
    phone_number = models.CharField(max_length=50, verbose_name='Telefon')
    academic_title = models.TextField(null=True, blank=True)
    position = models.CharField(max_length=200, null=True, blank=True) #Translation  --------

    is_chief = models.BooleanField(default=False)
    reception_time = RichTextUploadingField(null=True, blank=True) #Translation

    department = models.ForeignKey(Department, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Rectory(models.Model):  # rektorat
    name = models.CharField(max_length=200, verbose_name='F.I.O')
    image = models.ImageField(upload_to='./rectory/', verbose_name='Image')
    content = RichTextUploadingField(verbose_name="Information") #Translation
    academic_title = models.CharField(max_length=200, verbose_name='Academic Title') #Translation  ------
    address = models.TextField(verbose_name='Address', null=True, blank=True) #Translation

    phone_number = models.CharField(max_length=50, verbose_name='Phone Number', null=True, blank=True)
    fax_number = models.CharField(max_length=50, verbose_name='Fax Number', null=True, blank=True)
    email = models.EmailField(verbose_name='Email', null=True, blank=True)
    facebook = models.CharField(max_length=100, verbose_name='Facebook', null=True, blank=True)
    instagram = models.CharField(max_length=100, verbose_name='Instagram', null=True, blank=True)
    telegram = models.CharField(max_length=100, verbose_name='Telegram', null=True, blank=True)

    is_rector = models.BooleanField(default=False)
    position = models.CharField(max_length=250, verbose_name='Position') #Translation ------
    reception_time = RichTextUploadingField(verbose_name='Qabul vaqti') #Translation

    def __str__(self):
        return self.name


class Service(models.Model):
    name = models.CharField(max_length=200, verbose_name='Name')
    icon_class = models.CharField(max_length=250, verbose_name='Icon Name')
    url = models.URLField(verbose_name='Url')

    def __str__(self):
        return self.name


class Sahifalar(models.Model):
    title = models.CharField(max_length=255, verbose_name='Title')
    content = RichTextUploadingField(verbose_name='Content')
    page_name = models.CharField(max_length=255, verbose_name='Page url')

    def __str__(self):
        return self.page_name

main/views.py
from django.shortcuts import render
from .models import Partner, Department, Employee, Rectory, Service, Sahifalar
from fakultet.models import Chair, TeacherChair, Faculty, TeacherFaculty, New

def welcome(request):
    partners = Partner.objects.all() # hamkorlar
    faculties = Faculty.objects.all()
    news = New.objects.all()[:8]
    content = {
        'partners': partners,
        'faculties': faculties,
        'news': news
    }
    return render(request, 'main/welcome.html', content)

def gerb(request):
    content = {
        'faculties': Faculty.objects.all()
    }
    return render(request, 'main/ramzlar/gerb.html', content)

def bayroq(request):
    content = {
        'faculties': Faculty.objects.all()
    }
    return render(request, 'main/ramzlar/bayroq.html', content)

def madhiya(request):
    content = {
        'faculties': Faculty.objects.all()
    }
    return render(request, 'main/ramzlar/madhiya.html', content)

def vazifa(request):
    content = {
        'faculties': Faculty.objects.all()
    }
    return render(request, 'main/ramzlar/vazifa.html', content)

def rektorat(request):
    rectories = Rectory.objects.all()
    rector = None
    unrector = []
    for rectory in rectories:
        if rectory.is_rector:
            rector = rectory
        else:
            unrector.append(rectory)
    content = {
        'rector': rector,
        'rectories': unrector,
        'faculties': Faculty.objects.all()
    }
    return render(request, 'main/rektorat.html', content)


def qabul(request):

    content = {
        'faculties': Faculty.objects.all()
    }
    return render(request, 'main/qabulxona.html', content)

def store(request):  #chala
    pass

def xizmatlar(request):
    services = Service.objects.all()
    content = {
        'services': services,
        'faculties': Faculty.objects.all()
    }
    return render(request, 'main/xizmatlar.html', content)

def sahifalar(request, page):
    sahifa = Sahifalar.objects.get(page_name=page)
    content = {
        'sahifa': sahifa,
        'faculties': Faculty.objects.all(),
    }
    return render(request, 'main/page.html', content)

def markazlar(request):
    departments = Department.objects.all()
    content = {
        'departments': departments,
        'faculties': Faculty.objects.all()
    }
    return render(request, 'main/markazlar.html', content)

def markaz(request, pk):
    department = Department.objects.get(id=pk)
    employees = Employee.objects.filter(department=department)
    chief = None
    xodimlar = []
    for employee in employees:
        if employee.is_chief:
            chief = employee
        else:
            xodimlar.append(employee)
    content = {
        'department': department,
        'chief': chief,
        'employees': xodimlar,
        'faculties': Faculty.objects.all(),
    }
    return render(request, 'main/markaz.html', content)

def yangiliklar(request):
    news = New.objects.all()
    content = {
        'news': news,
        'faculties': Faculty.objects.all(),
    }
    return render(request, 'main/yangiliklar.html', content)

def yangilik(request, pk):
    new = New.objects.get(id=pk)
    news = New.objects.all()[:5]
    content ={
        'new': new,
        'news': news,
        'faculties': Faculty.objects.all(),
    }
    return render(request, 'main/yangilik.html', content)


def antikorrupsiya(request):
    content = {
        'faculties': Faculty.objects.all()
    }
    return render(request, 'main/korupsiya/korrupsiya.html', content)

templates/main/kafedralar.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="kafedra-title" style="background-image: url({% static '/assets/images/medik.jpg' %})">
        <p>Institut kafedralari</p>
        <ul>
            <li><a href="/">Asosiy page</a></li>
            <li><a href="#"></a></li>
        </ul>
    </div>
    <section class="kafedra-blog">
        <div class="kafedra-blogs">
            {% for chair in chairs %}
                <div class="kafedra">
                    <a href="#">
                        <i class="fa fa-graduation-cap"></i>
                        <h3 class="kafedra-name">
                            {{ chair.name }}
                        </h3>
                    </a>
                </div>
            {% endfor %}
            <div class="kafedra">
                <a href="https://admin.tsdi.uz/admin">
                    <i class="fa fa-sign-out"></i>
                    <h3 class="kafedra-name">
                        Login
                    </h3>
                </a>
            </div>
            <div class="kafedra">
                <a href="https://admin.tsdi.uz/admin">
                    <i class="fa fa-sign-out"></i>
                    <h3 class="kafedra-name">
                        Login
                    </h3>
                </a>
            </div>
            <div class="kafedra">
                <a href="https://admin.tsdi.uz/admin">
                    <i class="fa fa-sign-out"></i>
                    <h3 class="kafedra-name">
                        Login
                    </h3>
                </a>
            </div>
            <div class="kafedra">
                <a href="https://admin.tsdi.uz/admin">
                    <i class="fa fa-sign-out"></i>
                    <h3 class="kafedra-name">
                        Login
                    </h3>
                </a>
            </div>
            <div class="kafedra">
                <a href="https://admin.tsdi.uz/admin">
                    <i class="fa fa-sign-out"></i>
                    <h3 class="kafedra-name">
                        Login
                    </h3>
                </a>
            </div>
            <div class="kafedra">
                <a href="https://admin.tsdi.uz/admin">
                    <i class="fa fa-sign-out"></i>
                    <h3 class="kafedra-name">
                        Login
                    </h3>
                </a>
            </div>
        </div>
    </section>
{% endblock %}

templates/main/markaz.html
{% extends 'base.html' %}

{% block content %}
    <section class="kafedra-section">
        <div class="kafedra-single">

            <div class="mudir">
                <i class="mudir-i fa fa-arrow-down"></i>
                <span><img src="{{ chief.image.url }}" alt=""/></span>
                <span class="mudir-info">
                    <h1>{{ chief.name }}</h1>
                    <h3>{{ chief.position }}</h3>
                    <ul>
                        <li><i class="fa fa-phone"></i>{{ chief.phone_number }}</li>
                        <li><i class="fa fa-graduation-cap"></i>{{ chief.academic_title }}</li>
                        <li><i class="fa fa-envelope"></i>{{ chief.email }}</li>
                        <li><i class="fa fa-clock-o"></i>{{ chief.reception_time |safe }}</li>
                    </ul>
                </span>
            </div>

            <div class="xodimlar">
                {#                        @if($xodim[0]['blog_id']=='Raqamli ta’lim texnologiyalari markazi')#}
                {#                        <span class="xodim">#}
                {#                            <img class="markaz-image" src="https://tsdi.uz/storage/sahifas/photo_2020-06-17_09-56-58.jpg" alt="rasm"/>#}
                {#                            <ul>#}
                {#                            <h4>Qoraboyev Saidazim Saydali o`g`li</h4>#}
                {#                                <li><i class="fa fa-user"></i>Web dizayner</li>#}
                {#                                <li><i class="fa fa-phone"></i>+99891 151-31-17</li>#}
                {#                                <li><a href="https://t.me/Developer1524"><i class="fa fa-paper-plane"></i>@Developer1524</a></li>#}
                {#                                <li style="color:brown"><i class="fa fa-gavel"></i>{{ __('main.myjob') }}</li>#}
                {#                            </ul>#}
                {#                        </span>#}
                {#			                @endif#}

                {% for employee in employees %}
                    <span class="xodim">
                        <img class="markaz-image" src="{{ employee.image }}" alt="rasm"/>
                        <ul>
                            <h4>{{ employee.name }}</h4>
                            <li><i class="fa fa-user"></i>{{ employee.academic_title }}</li>
                            <li><i class="fa fa-phone"></i>{{ employee.phone_number }}</li>
					        <li><a href="{{ employee.email }}"><i class="fa fa-envelope"></i>{{ employee.email }}</a></li>
					        <li style="color:brown"><i class="fa fa-gavel"></i>{{ employee.position }}</li>
                        </ul>
                    </span>
                {% endfor %}

            </div>

            <h2>{{ department.name }}</h2>
            <p class="news-text">{{ department.content |safe }}</p>

            {#            <p class="news-icon"><span><i class="fa fa-calendar"></i> 28.10.2021 <i class="fa fa-eye"></i> 234 </span>#}
            {#            </p>#}

        </div>
    </section>


{% endblock %}

templates/main/markazlar.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="markaz-title" style="background-image: url({% static 'assets/images/medik.jpg' %})">
        <p>Markaz va bo'limlar</p>
        <ul>
            <li><a href="/">Asosiy sahifa</a></li>
            <li><a href="#"></a></li>
        </ul>
    </div>
    <section class="markaz-blog" style="background-image:url(https://www.gov.uz/img/title_bg.png)">
        <div class="markaz-blogs">
            {% for department in departments %}
                <div class="markaz">
                    <a href="{% url 'main:markaz' department.id %}">
                        <i class="fa fa-graduation-cap"></i>
                        <h3 class="markaz-name">
                            {{ department.name }}
                        </h3>
                    </a>
                </div>
            {% endfor %}
        </div>
    </section>

{% endblock %}

templates/main/page.html
{% extends 'base.html' %}

{% block content %}

    <div class="page-content content sahifa-mobile">
        <div class="blog" style="overflow-x:auto; background: #FFF">
            <h2 class="madhiya-title">{{ sahifa.title }}</h2>
            <p class="page-body">{{ sahifa.content|safe }}</p>
        </div>
    </div>

{% endblock %}

templates/main/welcome.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="welcome">
        <div class="corusel">
            <div class="slider">
                <nav class="slide-box">
                    <nav class="institut-name">
					<span>
						<h1>Toshkent Davlat Stomotologiya Institut</h1>
					</span>
                    </nav>
                    <img src="{% static 'assets/images/slider/stom.png' %}" alt="rasm"/>
                </nav>
            </div>
        </div>

        <section class="havolalar">
            <br><br><br>
            <div class="havola">
            <span class="h-blog">
                <i style="background-color: #51e2f5" class="fa fa-user"></i>
                <a href="{% url 'faculty:fakultetlar' %}"><p>Fakultetlar</p></a>
            </span>
                <span class="h-blog">
                <i style="background-color: #a28089" class="fa fa-users"></i>
                <a href="{% url 'faculty:kafedralar' %}"><p>Kafedralar</p></a>
            </span>
                <span class="h-blog">
                <i style="background-color: #34568B" class="fa fa-maxcdn"></i>
              <a href="{% url 'main:markazlar' %}"><p>Markaz va bo'limlar</p></a>
            </span>
                <span class="h-blog">
                <i style="background-color: #88B04B" class="fa fa-folder-open"></i>
               <a href="https://student.tsdi.uz/dashboard/diploma"><p>Diplomni tasdiqlash</p></a>
            </span>
                <span class="h-blog">
                <i style="background-color: #45B8AC" class="fa fa-envelope-o"></i>
                <a href="https://e-xat.tsdi.uz/"><p>e-Xat</p></a>
            </span>
                <span class="h-blog">
                <i style="background-color: orange" class="fa fa-graduation-cap"></i>
                <a href="https://moodle.tsdi.uz/login/index.php"><p>Moodle tizimi</p></a>
            </span>
                <span class="h-blog">
                <i style="background-color: #3c8dbc" class="fa fa-users"></i>
                <a href="https://hemis.tsdi.uz/dashboard/login"><p>Hemis-o'qituvchi</p></a>
            </span>
                <span class="h-blog">
                <i class="fa fa-graduation-cap"></i>
                <a href="https://student.tsdi.uz/dashboard/login"><p>Hemis-talaba</p></a>
            </span>
                <span class="h-blog">
                <i style="background-color: #3c556e" class="fa fa-book"></i>
                <a href="https://library.tsdi.uz/"><p>Kutubxona</p></a>
            </span>
                <span class="h-blog">
                <i style="background-color: purple" class="fa fa-server"></i>
                <a href="{% url 'main:xizmatlar' %}"><p>i-Xizmatlar</p></a>
            </span>
            </div>
        </section>

        <section class="i-servsec">
            <div class="i-service">
                <h1 class="section-title"><label>Statistik Ko'rsatkichlar</label></h1>
                <p class="section-shortitle">Institut ta`lim jarayonidagi asosiy ko`rsatkichlar</p>
                <br><br>
                <div class="services">
                    <nav class="service">
                        <p id="xt" class="number"> Tadqiqodchilar soni 186</p>
                        <p class="who">Tadqiqodchilar jami 26 ta ixtisoslikda izlanish olib bormoqda</p>
                    </nav>
                    <nav class="service">
                        <p id="pro" class="number">Professorlar soni 225</p>
                        <p class="who">Institutda jami 552 ta o`qituvchilar faoliyat olib bormoqda</p>
                    </nav>
                    <nav class="service">
                        <p id="bt" class="number">Xorijiy talabalar 4742</p>
                        <p class="who">Institutda jami 4808 ta talaba tahsil olmoqda</p>
                    </nav>
                </div>
            </div>
        </section>

        <!-- Yangiliklar -->
        <section class="news-box-sec">
            <div class="news-box">
                <div class="news">
                    {% for new in news %}
                        <span class="new">
				            <em class="newstime">{{ new.create_at|date:'d-m-Y' }} |{{ new.create_at|time:'H:i' }}</em>
                            <a class="new-a" href="{% url 'main:yangilik' new.id %}">
               		            <div>
                                    <img src="{{ new.image.url }}" alt="Yangiliklar"/>
                                </div>
               		            <div class="matn-box">
                                    <p class="matn" id="text">
                                        <i class="fa fa-address-card-o"></i>
                                        {{ new.title|slice:106}}
                                    </p>
                                </div>
                            </a>
                        </span>
                    {% endfor %}
                </div>
            </div>
        </section>

        <section class="institut-sect">
            <div class="institut">
                <h1 class="section-title"><label>Toshkent Davlat Stomotologiya Instituti</label></h1>
                <br><br><br>
                <div class="videos">
            <span class="main-video">
				<video id="myvideo" width="100%" height="100%" controls="controls">
  					<source src="{% static 'assets/media/welcome/main.webm' %}" type="video/mp4">
  					<source src="movie.ogg" type="video/ogg">
				</video>
            </span>
                    <span class="addition">
                <span class="video">
                	<video id="myvideo" width="100%" height="100%" style="border-radius: 5px;" controls="controls">
  						<source src="{% static 'assets/media/welcome/manaviyat.webm' %}" type="video/mp4">
  						<source src="movie.ogg" type="video/ogg">
					</video>
                </span>
                <span class="video">
                	<video id="myvideo" width="100%" height="auto" style="border-radius: 5px;" controls="controls">
  						<source src="{% static 'assets/media/welcome/media.webm' %}}" type="video/mp4">
  						<source src="movie.ogg" type="video/ogg">
					</video>
                </span>
            </span>
                </div>
            </div>
        </section>

        <!-- Hamkorlar -->
        <section class="hamkor-box">
            <div class="hamkorlar" id="hamkor-scrol">
                {% for partner in partners %}
                    <nav class="hamkor">
                        <a href="{{ partner.url }}">
                            <img src="{{ partner.image.url }}" alt="Hamkor"/>
                            <p class="hamkor-name">{{ partner.name }}</p>
                        </a>
                    </nav>
                {% endfor %}
            </div>
        </section>

        <section class="statistika_bottom">

            <div class="content">
			<span>
				<h2>Institut haqida</h2>
				<p>Taʼlim maskanida darslar anʼanaviy tazrda oʻtkaziladi, talabalarning stomatologiya sohasini
                    chuqur egallashlari uchun yetarli sharoitlar yaratilgan.
                    Talabalikka qaboʻl qilingan oʻquvchilar institutni maxsus kartalari bilan taʼminlanadi,
                    labaratoriya xonalarida va maʼruza xonalarida darslar olib boriladi.</p>
			</span>
                <nav>
                    <p>Asos solingan</p>
                    <h2>2014</h2>

                </nav>
                <nav>
                    <p>Fakultetkar soni</p>
                    <h2>5</h2>

                </nav>
                <nav>
                    <p>Kafedralar soni</p>
                    <h2>32</h2>

                </nav>
            </div>

        </section>
    </div>
{% endblock %}

templates/main/xizmatlar.html
{% extends 'base.html' %}
{% block content %}
    <style>
        .h-blog i {
            color: #9457EB !important;
            background-color: #FFF !important;
        }

        .h-blog p {
            color: #9457EB !important;
        }
    </style>
    <section class="havolalar">
        <div class="havola">
            {% for service in services %}
                <span class="h-blog">
                    {{ service.icon_class | safe }}
                    <a href="{{ service.url }}"><p>{{ service.name }}</p></a>
                </span>
            {% endfor %}
        </div>
    </section>
{% endblock %}

templates/main/yangilik.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <style>
        .news-blog {
            overflow: hidden;
        }
        .news-blog img {
        }
    </style>
    <div>
        <div class="kafedra-title" style="background-image: url({% static 'assets/images/medik.jpg' %})">
            <p>Institut yangililari</p>
            <ul>
                <li><a href="/">Asosiy sahifa</a></li>
                <li><a href="#"></a></li>
            </ul>
        </div>
        <section class="news-section">
            <div class="news-blogs">
                <div class="news-blog-outer">
                    <div class="news-blog">
                        <h2 class="news-name">
                            {{ new.title }}
                        </h2>
                        <p id="htmlContent" class="news-text">
                            {{ new.content | safe }}
                            <br>
                        </p>
                        <p class="news-icon"><span><i class="fa fa-calendar"></i> {{ new.create_at }} </span>
                            <span><a href="" onclick="display()"><i class="fa fa-print"></i>
                             chop etish </a></span></p>
                    </div>
                </div>
                <div class="last-news" style="background: transparent">
                    <h3>So'ngi yangiliklar</h3>
                    {% for post in news %}
                        <div class="last-new" style="margin-top: 0">
                            <a href="{% url 'main:yangilik' post.id %}">
                                <p class="last-news-text">{{ post.title }}</p>
                                <p class="news-icon"><i class="fa fa-calendar"></i>
                                    {{ post.create_at|date:'d-m-Y' }} |{{ post.create_at|time:'H:i' }}</p>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    </div>
    <script>
        function display() {
            window.print();
        }
    </script>

{% endblock %}

templates/main/yangiliklar.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <style>
        .pagination {
            display: flex;
            column-gap: 25px;
            margin-top: 30px
        }
        .pagination .page-item {
            background-color: rgb(46, 39, 81, 0.8);
            display: flex;
            width: 30px;
            height: 30px;
            align-items: center;
            justify-content: center;
            border-radius: 2px;
        }
        .pagination .page-item .page-link {
            color: #FFF;
        }
        .pagination .page-item span {
            display: flex;
            width: 30px;
            height: 30px;
            background-color: rgb(255, 255, 255);
            border: 1px solid rgb(46, 39, 81);
            border-radius: 2px;
            color: rgb(46, 39, 81) !important;
            align-items: center;
            justify-content: center;
        }
    </style>
    <div class="kafedra-title" style="background-image: url({% static 'assets/images/medik.jpg' %})">
        <p>Institut Yangiliklari</p>
        <ul>
            <li><a href="/">Asosiy sahifa</a></li>
            <li><a href="#"></a></li>
        </ul>
    </div>
    <section class="news-box yangiliklar" style="background-image:url('https://tsdi.uz/assets/images/background.png')">
        <div class="news">
            {% for new in news %}
                <span class="new">
				    <em class="newstime">{{ new.create_at|date:'d-m-Y' }} |{{ new.create_at|time:'H:i' }}</em>
                    <a href="{% url 'main:yangilik' new.id %}">
                        <img src="{{ new.image.url }}" alt="Yangiliklar"/>
                        <p class="matn" id="text"><i class="fa fa-address-card-o"></i>{{ new.title }} </p>
                    </a>
                </span>
            {% endfor %}
            {#            {!! $post->links() !!}#}
        </div>
    </section>
{% endblock %}