fakultet/urls.py
from django.urls import path
from . import views

app_name = 'faculty'
urlpatterns = [
    path('fakultetlar/', views.faculties_view, name='fakultetlar'),
    path('fakultet/<str:sub_name>/', views.faculty_view, name='fakultet'),
    path('kafedralar/', views.kafedralar_view, name='kafedralar'),
    path('kafedra/<str:sub_name>/', views.kafedra_view, name='kafedra'),
]

main/urls.py
from django.urls import path
from . import views

app_name='main'

urlpatterns = [
    path('', views.welcome, name='welcome'),
    path('gerb/', views.gerb, name='gerb'),
    path('bayroq/', views.bayroq, name='bayroq'),
    path('madhiya/', views.madhiya, name='madhiya'),
    path('vazifa/', views.vazifa, name='vazifa'),
    path('rektorat/', views.rektorat, name='rektorat'),
    path('qabulxona/', views.qabul, name='qabulxona'),
    # path('qabulxona/xabar', views.store, name='xabar'),           shu yer chala
    path('i-xizmatlar/', views.xizmatlar, name='xizmatlar'),
    path('sahifa/<str:page>/', views.sahifalar, name='sahifa'),
    path('markazlar/', views.markazlar, name='markazlar'),
    path('markaz/<int:pk>/', views.markaz, name='markaz'),
    path('yangiliklar/', views.yangiliklar, name='yangiliklar'),
    path('yangilik/<int:pk>/', views.yangilik, name='yangilik'),
    path('antikorrupsiya/', views.antikorrupsiya, name='antikorrupsiya'),

]

tsdi_uz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = i18n_patterns(
    path('', include('main.urls', namespace='main')),
    path('', include('fakultet.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('ckeditor/', include('ckeditor_uploader.urls')),

)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fakultet/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField

class Chair(models.Model):  #Kafedralar
    name = models.CharField(max_length=255, verbose_name='Kafedra nomi') #translation
    sub_name = models.CharField(max_length=100, verbose_name='Subdomain nomi')
    content = RichTextUploadingField(null=True, blank=True, verbose_name='Kafedra haqida') #translation

    def __str__(self):
        return self.name


class New(models.Model):  #Yangiliklar
    title = models.CharField(max_length=255, verbose_name='Yangiliklar') #Translation
    image = models.ImageField(upload_to='./news/', default='/news/news.png')
    chair = models.ManyToManyField(Chair, blank=True, verbose_name='Kafedra news')
    content = RichTextUploadingField(null=True, blank=True, verbose_name='Yangilik haqida') #translation
    sees = models.IntegerField(default=1)

    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def see_add(self):
        self.sees = self.sees + 1
        self.save()

    def __str__(self):
        return self.title


class TeacherChair(models.Model):  #Kafedra o'qituvchilari
    name = models.CharField(max_length=150, verbose_name='Ism Familya')
    chair = models.ForeignKey(Chair, verbose_name='kafedra name', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='./kafedra/', default='./kafedra/avatar.png', verbose_name='Rasm Ustoz')

    position = models.TextField(verbose_name='Ustoz haqida', null=True, blank=True) #tranlation
    academic_title = models.CharField(max_length=250, null=True, blank=True, verbose_name='Ustoz darajasi') #translation

    phone_num = models.CharField(max_length=200, verbose_name='Telefon nomer')
    email = models.CharField(max_length=200, verbose_name='Ustoz Email')

    def __str__(self):
        return self.name


class Faculty(models.Model): #Fakultet
    name = models.CharField(max_length=250, verbose_name='Fakultet nomi')  #Translation
    sub_name = models.CharField(max_length=250, verbose_name='Fakultet_name', null=True, blank=True)
    content = RichTextUploadingField(blank=True, null=True, verbose_name='Fakultet haqida')  #Translation
    kafedra = models.ManyToManyField(Chair, verbose_name='kafedralar')

    def __str__(self):
        return self.name


class TeacherFaculty(models.Model): #fakultet dekanlar
    name = models.CharField(max_length=250, verbose_name='Ustoz ismi')
    image = models.ImageField(upload_to='./fakultet/', default='/fakultet/avatar.png')
    fakultet = models.ForeignKey(Faculty, on_delete=models.CASCADE)
    academic_title = models.TextField(null=True, blank=True, verbose_name='Academic title') # Translation

    phone_number = models.CharField(max_length=250, null=True, blank=True, verbose_name='Telefon nomer')
    email = models.EmailField(max_length=200, verbose_name='Email', null=True, blank=True)
    reception_time = RichTextUploadingField(null=True, blank=True, verbose_name='Qabul vaqti')

    position = models.CharField(max_length=250, verbose_name='Position', null=True, blank=True)
    is_dean = models.BooleanField(default=False, verbose_name='Dekanmi?')

    def __str__(self):
        return self.name

fakultet/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Chair, TeacherChair, New, Faculty, TeacherFaculty


def faculties_view(request):
    faculties = Faculty.objects.all()
    content = {
        'faculties': faculties,
    }
    return render(request, 'fakultet/fakultetlar.html', content)


def faculty_view(request, sub_name):
    faculty = Faculty.objects.get(sub_name=sub_name)
    faculties = Faculty.objects.all()
    chairs = faculty.kafedra.all()
    content = {
        'faculty': faculty,
        'faculties': faculties,
        'chairs': chairs,
    }
    return render(request, 'fakultet/fakultet.html', content)


def kafedralar_view(request):
    kafedralar = Chair.objects.all() # kafedralar
    content = {
        'kafedralar': kafedralar,
    }
    return render(request, 'kafedra/kafedralar.html', content)

def kafedra_view(request, sub_name):
    kafedra = Chair.objects.get(sub_name=sub_name)
    news = New.objects.filter(chair=kafedra)
    print(request.path_info)
    paths = request.path_info.strip('/').split('/')
    print(paths)

    content = {
        'kafedra': kafedra,
        'news': news
    }
    return render(request, 'kafedra/home/home.html', content)


def news_view(request):
    return render(request, 'kafedra/home/news.html')


def xodim(request):
    return render(request, 'kafedra/home/xodim.html')


def about(request):
    return render(request, 'kafedra/home/about.html')

templates/fakultet/fakultet.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div>
        <div class="fakultet-title" style="background-image: url({% static 'assets/images/medik.jpg' %})">
            <p>Institut fakultetlari</p><br>
            <ul>
                <li><a href="/">Asosiy sahifa</a></li>
                <li><a href="#"></a></li>
            </ul>
        </div>
        <section class="fakultet-blog">
            <div class="fakultet-content">
                <div class="fakultet-blogs">
                    {#                    @foreach ($data as $item)#}

                    <div class="f-blog">
                        <h2 class="fakultet-name">{{ faculty.name }}</h2>

                        <span class="blog">
{#                            @foreach ($xodim as $info)#}
{#                            @if ( $info['blog_id'] == $item['nom'] && $info['job'] == 'option2')#}
{#                                <img src="" alt=""/>#}
{#                                <span class="dekan">#}
{#                                    <ul>#}
{#                                    	<li><b>{{ __('main.dekan') }} </b>{{ $info['name'] }}</li>#}
{#                                    	<li><i>{{ $info['idu'] }}</i></li>#}
{#                                    	<li><b>{{ __('main.telefon') }} </b>{{ $info['nomer'] }}</li>#}
{#                                    	<li><b>E-mail: </b>{{ $info['mail'] }}</li>#}
{#                                    	<li><b>{{ __('main.muddat') }} </b>{{ $info['manzil'] }}</li>#}
{#                                    	<li><b>{{ __('main.qabul_v') }} </b>{{ __('main.harkuni') }} 14<sup>00</sup>-18<sup>00</sup></li>#}
{#                                    </ul>#}
{#                                </span>#}
{#                            @endif#}
{#                            @endforeach#}
                        </span>

                        <span class="zamdekan">
{#                                @foreach ($xodim as $info)#}
{#                                @if ( $info['blog_id'] == $item['nom'] && $info['job'] == 'zamdekan')#}

{#                                <div>#}
{#                                    <nav>#}
{#                                    	<p>{{ $info['name'] }}</p>#}
{#                                    	<ul>#}
{#                                        	<li><i class="fa fa-phones"></i>{{$info['nomer']}}</li>#}
{#                                        	<li><i class="fa fa-envelopes"></i>{{$info['mail']}}</li>#}
{#                                    	</ul>#}
{#                                     </nav>#}
{#                                </div>#}

{#                                @endif#}
{#                                @endforeach#}
                            </span>

                        <div class="about sf">
{#                            <h3>{{ faculty.name }}</h3>#}
                            <p>{{ faculty.content|safe }}</p>
                        </div>
                    </div>

{#                    @endforeach#}
                </div>
                <div class="kafedra-blogs-w">
                    {% if chairs %}
                        <nav>
                            <h3>Kafedralar</h3>
                            {% for chair in chairs %}
                                <a href="{% url 'faculty:kafedra' chair.sub_name %}"><p>{{ chair.name }} </p></a>
                            {% endfor %}
                        </nav>
                        <br>
                    {% endif %}

                    <nav>
                        <h3>Fakultetlar</h3>
                        {% for facult in faculties %}
                            <a href="{% url 'faculty:fakultet' facult.sub_name %}"><p>{{ facult.name }}</p></a>
                        {% endfor %}

                    </nav>

                </div>

            </div>
        </section>
    </div>
{% endblock %}

templates/fakultet/fakultetlar.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="kafedra-title" style="background-image: url({% static 'assets/images/medik.jpg' %})">
        <p>Fakultetlar</p>
        <ul>
            <li><a href="/static">Asosiy sahifa</a></li>
            <li><a href="#"></a></li>
        </ul>
    </div>
    <section class="kafedra-blog">
        <div class="kafedra-blogs">
        {% for faculty in faculties %}
        <div class="kafedra">
                <a href="{% url 'faculty:fakultet' faculty.sub_name %}">
                <i class="fa fa-graduation-cap"></i>
                <h3 class="kafedra-name">
                    {{ faculty.name }}
                </h3>
                </a>
            </div>
        {% endfor %}
          	<div class="kafedra">
                <a href="https://admin.tsdi.uz/admin">
                <i class="fa fa-sign-out"></i>
                <h3 class="kafedra-name">
                    Login
                </h3>
                </a>
            </div> 
        </div>
    </section>
{% endblock %}